# module_description: this moudule reads the *.recon file from /var/cache/swift directory, and parse
# data such as replication time, object audit time...etc. Generally speaking, this is the module that
# contains data most users will find useful.
ReadReconFile: yes
# module_description: this module checks Swift nodes and grab information about disk.
# Enter "yes" to enable, and "no" to disable.
SwiftDiskUsage: yes
# module_description: this module pull disk IO stats from all Swift drives (those that are mounted in "/srv/node/d<x>")
# and expose them via Prometheus.
SwiftDriveIO: yes
# module_description: this module will read the latest entry in all.log and search for keyword "replicated",
# then extract the data out and parse for the estimated time complete, and part/sec. Enter "yes" to enable,
# and "no" to disable.
GatherReplicationEstimate: yes
# module_description: this module grabs the size of each drive that has a storage policy assigned to it,
# then expose it to Prometheus.
#GatherStoragePolicyUtilization: yes
GatherStoragePolicyUtilization: no
# module_description: this module checks the number of object server spinned. This is useful for replica based storage policy.
# The number of object server = number of drives * object server per port setting.
CheckObjectServerConnection: yes
# module_description: this module expose cpu usage and expose them in prometheus.
#ExposePerCPUUsage: yes
ExposePerCPUUsage: no
# module_description: this module expose cpu usage and expose them in prometheus.
#ExposePerNICMetric: yes
ExposePerNICMetric: no
SwiftVersion: "2.15.1"
SwiftLogFile: "/var/log/swift/swift.log"
SwiftConfigFile: "/etc/swift/swift.conf"
#ReplicationProgressFile: "/var/log/swift/swift_exporter_replication_progress.json"
ObjectReconFile: "/var/cache/swift/object.recon"
ContainerReconFile: "/var/cache/swift/container.recon"
AccountReconFile: "/var/cache/swift/account.recon"

